### ISSUE TITLE
[Bug]: Armor bar not using resource pack icons

### ISSUE THREAD

**Issue by ACE1337x** [Fuzss/overflowingbars#35]
### Mod Loader (Required)

Forge

### Minecraft Version(s) (Required)

1.20.1

### Mod Version(s) (Required)

v8.0.1

### Minimal Setup (Required)

Yes

### Notes (Required)

The armor bar does not use the armor icons from the active resource pack

1. Install the mod
2. Install resource packs that have different armor icons
3. Equip armor

### latest.log (Required)

https://gist.github.com/ACE1337x/bf350309fd76306bde0541fcf1acf92b

**Comment by Fuzss** [comment]
That's just how the mod works. Replacing vanilla icons is necessary to be able to support rendering halves.
You can manually create a resource pack from the assets of your current pack.

**Comment by creaturesnhjgurewas** [comment]
> That's just how the mod works. Replacing vanilla icons is necessary to be able to support rendering halves. You can manually create a resource pack from the assets of your current pack.

hello, i'm sincerely sorry if this is an annoyance as i'm just getting into modded minecraft. i don't understand exactly what you mean, could you please explain how to do this or link a resource/guide? i understand the purpose of being able to render halves and the concept of copying assets to create a resource pack but where do i put that resource pack in order to change overflowing bars? thank you very much and i apologize for any inconvenience.
